Howto/early stopping
google/flax pull request #1528
Opened 2021-09-08 19:14 UTC by INF800

How to documentation for early stopping

2021-09-08 19:25 UTC, INF800 commented on .gitignore
> +.venv/
For github codespaces

2021-09-13 01:09 UTC, INF800 commented
@marcvanzee @avital let me know if this looks good.

2021-09-23 14:54 UTC, avital commented
Hi @INF800 -- please take a look at what the rendered doc looks lke: https://flax--1528.org.readthedocs.build/en/1528/howtos/early_stopping.html

It show a nice side-by-side diff view with the original training loop on the left and the modified version with early stopping (and everything else as well) on the right side.

Take a look at the following for an example: https://flax.readthedocs.io/en/latest/howtos/ensembling.html

Also please take a careful look at formatting and re-read it multiple times, as it stands there are some misformed sentences and the explanation can be improved.

2022-02-20 09:56 UTC, marcvanzee requested changes
Thanks for the HOWTO!
It would be great if you could add a Colab with this change as well so we can test it actually works.

Are you still planning on finishing this? (It is a while ago already since it has been created)

2022-02-20 09:56 UTC, marcvanzee commented on .gitignore
> +.venv/
Please add a newline

2022-02-20 09:56 UTC, marcvanzee commented on docs/howtos/early_stopping.rst
> +* Train loss is decreasing but the decrease in loss is is insignificant.
```suggestion
- Train loss not decreasing at all.
- Train loss is decreasing but the decrease in loss is is insignificant.
```

2022-02-20 09:56 UTC, marcvanzee commented on docs/howtos/early_stopping.rst
> +Early stopping is used while building model to stop training loop when specific conditions are met. Some such conditions are:
Can you please just copy/paste a definition of early stopping? This sentence is a bit hard to parse.

2022-02-20 09:56 UTC, marcvanzee commented on docs/howtos/early_stopping.rst
> +* Train loss is decreasing but the decrease in loss is is insignificant.
The second condition repeats the first one

2022-02-20 09:56 UTC, marcvanzee commented on docs/howtos/early_stopping.rst
> +A sample training loop looks like this
Can you use syntax highlighting here for the codediff blocks like in the enselmbing HOWTO? https://github.com/google/flax/blob/main/docs/howtos/ensembling.rst

You have to append "#!" to each line you want to highlight

2022-02-22 08:33 UTC, INF800 commented
Sorry for the delay. I was under the impression that it this was merged. Will send PR by end of weekend.

2022-04-28 19:14 UTC, marcvanzee commented
@INF800 any updates on this? Note I improved the docstring for Early Stopping in #2090 by adding a minimal example.

2022-05-12 07:53 UTC, marcvanzee commented
@INF800 I am closing this PR due to inactivity, and like I said we have now a minimal example in our docstring already.

2022-05-12 07:53 UTC, closed without merging