Draft: re-do docs landing page
google/flax pull request #1666
Opened 2021-11-09 15:51 UTC by avital

Try a first attempt at a full re-haul of the RTD landing page with more explicit calls to action. This is a starting point for future exploration.

2021-11-09 17:41 UTC, 8bitmp3 commented on docs/index.rst
> +which are showcased with end-to-end integrated guides and examples. |emphasized hyperlink|_
@saeta You feedback would be appreciated.

2021-11-09 18:42 UTC, andsteing requested changes
It's great to see this ball rolling...

First round of comments - there will probably be lots of iterations on this PR :)

2021-11-09 18:42 UTC, andsteing commented on docs/index.rst
> +.. code:: python
Could you add a link to a working Colab for this?

2021-11-09 18:42 UTC, andsteing commented on docs/index.rst
> +   class MLP(nn.Module):
What about using an example that highlights Flax's strengths a bit better?

The challenge will be to keep it short and understandable. I think it's fine if the reader does not understand all the code, but they should be able to understand what is happening, and ideally be impressed by Flax's brevity and great flexibility to tackle difficult problems...

2021-11-16 16:26 UTC, saeta commented on docs/index.rst
Silly idea; feel free to use it or ignore it:

```suggestion
Flax delivers a **comprehensive platform** for JAX-based researchers, emphasizing **productivity, and flexibility without compromising the full power of JAX's composable function transformations**. Flax's features enable researchers to scale from a single local CPU/GPU up to massive TPU pods [1](http://todo/link-to-t5x-and-related-documentation).
Flax is made up of loosely coupled libraries,
which are showcased with end-to-end integrated guides and examples. |emphasized hyperlink|_
```

2022-11-30 12:44 UTC, marcvanzee commented
Closing this since @cgarciae took this over in #2177.

Thanks for starting this @avital!

2022-11-30 12:44 UTC, closed without merging