Update download_dataset_metadata.sh
google/flax pull request #1801
Opened 2022-01-23 22:00 UTC by mattiasmar

Use git sparse operation instead of svn.

# What does this PR do?
Removes the dependency on SVN.

Fixes # (issue)
Failed to use SVN behind enterprise firewall. With not negligible IT-skills this can probably be solved. Git on the other hand works well behind the firewall, and only requires one to define the http_proxy environment variable. 

## Checklist
- [ x] This PR fixes a minor issue (e.g.: typo or small bug) or improves the docs (you can dismiss the other
      checks if that's the case).
- [ x] This change is discussed in a Github [discussion]([link](https://github.com/google/flax/discussions/1773)).
- [ x] The documentation and docstrings adhere to the
      [documentation guidelines](https://github.com/google/flax/blob/main/docs/README.md#how-to-write-code-documentation).
- [ ] This change includes necessary high-coverage tests.  - No.  ./tests/run_all_tests.sh fails.
      (No quality testing = no merge!)

2022-02-28 03:58 UTC, levskaya requested changes
Wow - this is great!  SVN is a real pain in a lot of environments.  I hadn't noticed that the sparse-checkout was finally fully supported back in Git 2.25 in 2020.

I tested the timing quickly myself:
SVN checkout time: 18s
sparse git time: 7s

So this is even faster as well.   There's just one minor bug in the bash script that needs fixing and we can adopt this.

2022-02-28 03:58 UTC, levskaya commented on tests/download_dataset_metadata.sh
> +  rm datasets -rf
this needs to be `rm -rf datasets` to work.

2022-02-28 04:00 UTC, levskaya commented
@mattiasmar - so sorry for slow reply btw - a few of us have been out or sick lately - would you mind signing the CLA form as well?

2022-03-03 20:10 UTC, mattiasmar commented
I'm on vacation. If you share with me a link to the CLA I can review it next week.
________________________________
From: Anselm Levskaya ***@***.***>
Sent: Monday, February 28, 2022 5:00:54 AM
To: google/flax ***@***.***>
Cc: Marder, Mattias ***@***.***>; Mention ***@***.***>
Subject: Re: [google/flax] Update download_dataset_metadata.sh (PR #1801)


@mattiasmar<https://github.com/mattiasmar> - so sorry for slow reply btw - a few of us have been out or sick lately - would you mind signing the CLA form as well?

—
Reply to this email directly, view it on GitHub<https://github.com/google/flax/pull/1801#issuecomment-1053859844>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALPSDLAYXLOKJZGNAJ3DTDDU5LXPNANCNFSM5MT3ZLBQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
---------------------------------------------------------------------
Intel Israel (74) Limited

This e-mail and any attachments may contain confidential material for
the sole use of the intended recipient(s). Any review or distribution
by others is strictly prohibited. If you are not the intended
recipient, please contact the sender and delete all copies.

2022-03-04 02:55 UTC, levskaya commented
Thanks - there are instructions under the failing `cla/google` check with link to CLA.

2022-03-17 06:46 UTC, levskaya commented
@mattiasmar - I'd love to merge this if you get any time to fix the one script bug and check the CLA.  I'd love to axe the svn dependency.

2022-03-30 13:52 UTC, levskaya commented
@mattiasmar  - let me know if you get a chance to look over the above comment and CLA.  

And if you'd rather not sign it, just let me know and I can take over adding git `sparse-checkout` support to our CI script. I'd love to get rid of the svn dependency for good. Thanks!

2022-03-30 13:55 UTC, mattiasmar commented
Hi. I’m going through a corporate process to sign the CLA. Should be fine in a week or so.

From: Anselm Levskaya ***@***.***>
Sent: Wednesday, March 30, 2022 16:52
To: google/flax ***@***.***>
Cc: Marder, Mattias ***@***.***>; Mention ***@***.***>
Subject: Re: [google/flax] Update download_dataset_metadata.sh (PR #1801)


@mattiasmar<https://github.com/mattiasmar> - let me know if you get a chance to look over the above comment and CLA.

And if you'd rather not sign it, just let me know and I can take over adding git sparse-checkout support to our CI script. I'd love to get rid of the svn dependency for good. Thanks!

—
Reply to this email directly, view it on GitHub<https://github.com/google/flax/pull/1801#issuecomment-1083167924>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALPSDLHAM6BUU5Y6OYX2XWDVCRMBLANCNFSM5MT3ZLBQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
---------------------------------------------------------------------
Intel Israel (74) Limited

This e-mail and any attachments may contain confidential material for
the sole use of the intended recipient(s). Any review or distribution
by others is strictly prohibited. If you are not the intended
recipient, please contact the sender and delete all copies.

2022-05-04 11:06 UTC, mattiasmar commented
Under  "[Manage Agreements](https://cla.developers.google.com/clas)" it says that my user is covered by the "[Google Corporate CLA](https://cla.developers.google.com/about/google-corporate)", yet, the merging is blocked. Please advise.

2022-05-04 11:19 UTC, marcvanzee commented
> Under "[Manage Agreements](https://cla.developers.google.com/clas)" it says that my user is covered by the "[Google Corporate CLA](https://cla.developers.google.com/about/google-corporate)", yet, the merging is blocked. Please advise.

Did you verify the following?

* It's possible we don't have your GitHub username. Verify that [your existing CLA data](https://cla.developers.google.com/clas) is accurate.
* You may not be using the email associated with your CLA in your Git commits. Check that the [email set on your git commits](https://help.github.com/articles/setting-your-email-in-git/) matches the [email associated with your CLA](https://cla.developers.google.com/clas).

Maybe your email address in the commit doesn't match the one in the CLA?

2022-05-04 11:28 UTC, mattiasmar commented
I verified that the commit was done using my corporate email (the one covered by the CLA).

2022-05-04 11:29 UTC, marcvanzee commented
Great, looks good now!

2022-05-04 11:31 UTC, mattiasmar commented
The only thing I changed was doing an additional git commit (according to @levskaya's comment)/

2022-05-04 12:07 UTC, marcvanzee commented
Yes, that is sometimes necessary to retrigger the CLA check, quite annoying but it works now!

2022-05-24 02:28 UTC, merged

2022-05-24 03:17 UTC, levskaya commented
@mattiasmar - thanks so much for the improvement.  (Sorry my notifications somehow missed that the CLA went through, I hadn't wanted to hassle you again so I took forever to notice and merge this - apologies for that.)