Updates LR schedule HOWTO for optax
google/flax pull request #1903
Opened 2022-02-10 22:10 UTC by matthias-wright

This PR addresses #1577.

Note that I replaced the triangular scheduler with the cosine scheduler from the [imagenet example](https://github.com/google/flax/blob/cb5ebcd3b9ab8db10c79e88fcdb2dc67ce2668e2/examples/imagenet/train.py#L88) because the triangular scheduler did not play well with ``jit``. I think ``jit`` cannot trace the ``create_triangular_schedule`` function because of the if else that depends on the input.

2022-02-11 08:27 UTC, andsteing requested changes
So it seems the former HOWTO didn't actually work?
(Since the if..else problem is not something that has to do with Optax but rather a limitation of JIT)

This kind of proves the point that we should test these functions via doctest. Could you add some test code that covers the functions?

(sometimes we also link Colabs as starting points like in the `howtos/optax_update_guide.rst` but that's probably not needed here since this is rather short)

2022-02-11 08:27 UTC, andsteing commented on docs/howtos/lr_schedule.rst
> +    """Create learning rate schedule."""
nit: use descriptive-style in function pydoc:
https://google.github.io/styleguide/pyguide.html#383-functions-and-methods

2022-02-11 08:27 UTC, andsteing commented on docs/howtos/lr_schedule.rst
> +For example using this schedule on MNIST would require changing the train_step function:
nit: ``train_step``

2022-02-11 08:27 UTC, andsteing commented on docs/howtos/lr_schedule.rst
> +create_learning_rate_fn function and then pass the function to your ``optax`` optimizer.
nit: ``create_learning_rate_fn``

2022-02-11 08:27 UTC, andsteing commented on docs/howtos/lr_schedule.rst
>  And the train_epoch function:
nit: ``train_epoch``

2022-02-11 08:27 UTC, andsteing commented on docs/howtos/lr_schedule.rst
> +And the create_train_state function:
nit: ``create_train_state``

2022-02-11 08:27 UTC, andsteing commented on docs/howtos/lr_schedule.rst
> +create_learning_rate_fn function and then pass the function to your ``optax`` optimizer.
consider adding a link to the Optax docs somewhere:
https://optax.readthedocs.io/en/latest/api.html#optimizer-schedules

2022-02-11 09:39 UTC, matthias-wright commented
Thanks for the feedback! No, it didn't work, at least not in my environment. With doctests, do you mean blocks of ``.. testcode::`` and ``.. testoutput::`` that are visible in the HOWTO?

2022-02-14 21:04 UTC, matthias-wright commented
I only tested the ``train_step`` function for now because testing the ``train_epoch`` function takes around 2 minutes (on my machine).

2022-02-15 09:26 UTC, andsteing requested changes
Looks good, thanks for the updates!

I think you could indeed test `train_epoch()` (see file comment) and then the PR would be good to go.

2022-02-15 09:26 UTC, andsteing commented on docs/howtos/lr_schedule.rst
> +  state, metrics = train_step(state, batch, learning_rate_fn)
Why not set `config.train_ds_size=128` and then call `train_epoch()` instead? That shouldn't take significantly longer and would test all your code.

2022-02-15 09:27 UTC, andsteing commented on docs/howtos/lr_schedule.rst
> +.. testcode::
I think if you used `testsetup` here then it would still test it but not show it in the HOWTO, which would be preferable.

2022-02-15 20:10 UTC, matthias-wright commented
Thanks for the feedback! I had to use ``testcleanup`` instead of ``testsetup`` but the result is the same. The tests are executed during build but aren't visible in the HOWTO.

2022-02-16 06:55 UTC, andsteing approved these changes
Thanks for updating the HOWTO!
It's great to have it properly tested now...

2022-02-16 07:05 UTC, merged