Repo Analytics
google/flax pull request #2113
Opened 2022-05-11 15:53 UTC by cgarciae

# What does this PR do?
Adds a script to fetch and visualize metrics of the Flax repo from Github.

Closes #2108

2022-05-16 12:04 UTC, marcvanzee requested changes
Very cool! So it seems you can also very easily apply this to other repos, right? I think it would be cool to chat about this during the next sync with HuggingFace and ask them whether they are tracking any metrics.

Also, it may be useful for you to glance over the [Google Python Styleguide](https://google.github.io/styleguide/pyguide.html), which we try to follow as much as possible in our project (although we aren't perfect).

2022-05-16 12:04 UTC, marcvanzee commented on .github/analytics/issue_activity_since_date.gql
> +  repository(owner: "_REPO_OWNER_", name: "_REPO_NAME_") {
Could you add some comments to these files explaining what exactly they are querying?

2022-05-16 12:04 UTC, marcvanzee commented on .github/analytics/get_repo_metrics.py
> +  # TODO: Analyze PR data
This doesn't work yet? Or you just haven't looked at it yet?

2022-05-16 17:00 UTC, cgarciae commented
Thanks @marcvanzee!

> So it seems you can also very easily apply this to other repos, right?

Yes, I believe if you just change `google` and `flax` on `main` to any other user + repo it should work.

> Also, it may be useful for you to glance over the [Google Python Styleguide](https://google.github.io/styleguide/pyguide.html), which we try to follow as much as possible in our project (although we aren't perfect).

Yeah, sorry about that, most this code is ported from another project, I will fix it to match this project and remove references to non-existing stuff to avoid confusion.

2022-05-19 12:17 UTC, cgarciae commented
Added 2 metrics for the PRs and modified the ported code a bit to match our style.

2022-05-19 16:36 UTC, cgarciae commented
Many of the comments were about the ported code, I added a comment noting the source.
Also added comments explaining a bit what each query does.
Finally, last commit adds 2 metrics for PRs.

2022-05-20 05:17 UTC, marcvanzee approved these changes
Looks good now, thanks a lot!

2022-05-20 05:36 UTC, merged