Test-notebooks
google/flax pull request #2166
Opened 2022-05-31 20:13 UTC by cgarciae

# What does this PR do?

Uses `myst_nb` to render notebooks instead of `nbsphinx`. `myst_nb` executes the notebooks before rendering therefore it also serves as a testing mechanism for these.

2022-06-09 12:02 UTC, marcvanzee requested changes
Really nice and useful change @cgarciae! Few questions:
- Did you measure the impact on our CI runtime? I am curious how much longer it takes.
- IIUC then the generated .md files are not used for anything else except for simplifying modification of the notebooks, right? I wonder if at some point we can instead generate .rst files from them, then we could have our ideal situation of only having one source of truth for our HOWTOs.

2022-06-10 13:44 UTC, cgarciae commented on .github/workflows/build.yml
> +          python-version: 3.8
Yes, good catch!

2022-06-10 15:40 UTC, cgarciae commented on docs/contributing.md
> +### Update notebooks
This is ported from JAX docs, creddit goes to the JAX team :slightly_smiling_face:

2022-06-10 15:53 UTC, cgarciae commented on docs/contributing.md
> +git add docs -u  # pre-commit runs on files in git staging.
Added a section above with instructions on how to setup `pre-commit` as this will now be part of the main workflow.

2022-06-10 16:05 UTC, cgarciae commented
@marcvanzee 

> Did you measure the impact on our CI runtime? I am curious how much longer it takes.

Will get the numbers but for sure this will be slower :sweat_smile:, each cell is capped to a 100 seconds runtime though.

> IIUC then the generated .md files are not used for anything else except for simplifying modification of the notebooks, right? I wonder if at some point we can instead generate .rst files from them, then we could have our ideal situation of only having one source of truth for our HOWTOs.

HOWTOs that don't use any fancy sphinx feature can be written in notebook/markdown, no need to generate an `.rst` file since `myst_nb` will render it in html for us. I believe the motivation for the current setup is the `.. testsetup::` directive that hides some code while keeping the HOWTO executable right? `myst_nb`'s `hide-cell` and `remove-cell` tags can accommodate for this. I'll create an issue for this.

2022-06-10 17:04 UTC, cgarciae commented
@marcvanzee Here are the numbers, it add ~125 seconds. Note that `jax_for_the_impatient` is excluded for now. I think #2184 could help in this regard.

| | nbsphinx | myst_nb
|--|--|--|
|  time (secs) | 44.70 | 161.13 |

2022-06-14 19:52 UTC, cgarciae commented
> We also have the side-by-side diff view in our HOWTOs, I suppose this can't be used anymore then?

Yeah, I imagine it will not be easy to port those, there are a couple like the `model_surgery` HOWTO that don't use that mechanic which we could port right now.

2022-06-15 11:34 UTC, marcvanzee commented on .pre-commit-config.yaml
> +    args: [--sync]
```suggestion
    args: [--sync]

```

2022-06-15 11:47 UTC, marcvanzee commented
Looks good! The notebooks show a huge amount of diffs, but you only added the "Show in Colab" button right? It is so hard to review notebook changes in `.ipynb` format, which is another good argument for this change! 😄

2022-06-15 11:47 UTC, marcvanzee approved these changes

2022-06-15 11:47 UTC, marcvanzee commented on docs/contributing.md
> +git add docs -u  # pre-commit runs on files in git staging.
Thanks!

2022-06-16 02:01 UTC, cgarciae commented
@marcvanzee yeah git has a hard time with these large json files, hopefully we start relying on the markdown files from now on 😃

2022-06-22 06:56 UTC, merged