Adds extract_field method
google/flax pull request #2611
Opened 2022-11-14 21:24 UTC by cgarciae

# What does this PR do?

Fixes #2609. Adds the `Module.extract_field` method, useful to extract submodules that are defined inside `.setup` and their corresponding variables. 

#### Sample Usage

```python
class MyModule(nn.Module):
  def setup(self):
    self.submodule = nn.Dense(4)

  def __call__(self, x):
    return self.submodule(x)

module = MyModule()
variables = module.init(jax.random.PRNGKey(0), jnp.ones((1, 2)))

submodule, submodule_vars = module.extract_field('submodule', variables)
assert submodule.features == 4
```

Also works for nested object by passing a lambda:
```python
nested_module, nested_vars = module.extract_field(
  lambda m: m.some['deeply']['nested'].submodule, variables)

2022-11-17 10:19 UTC, marcvanzee commented
I like the idea and the general approach, but I am not so sure I like the interface, and I am also a bit confused about some things:

* the function is called `get_setup_field` but it returns a pair `(modules,  variables`). So it seems to return multiple modules and variables, which is different from what the function name indicates.

* in the function, you defined `unbounded_modules`, but it seems this can also be something else than modules so the name seems wrong?

Did you have a use case in mind for generalizing this function to something besides submodules? Right now it seems to be partially generalized, which could be part of the confusion.

Proposal: What do you think of the following interface?

```py
foo = Foo()  # some Flax Module
variables = foo.init(...)

submod, submod_vars = foo.submodule(variables, 'path/to/submodule')
```

This maintains the convention used to pass the variables (the state) as the first argument, and then adds a new argument that is the path to the submodule.

About error messages:

* It also seems useful to update [this error message](https://github.com/google/flax/blob/722838ce11e6b0b307dc6cdf44b4fa3175ead3a9/flax/linen/module.py#L811).

* Maybe we should also throw an error if a user would like to call this method on a Module that does not have a `setup` method.

2022-11-17 18:46 UTC, cgarciae commented
Hey @marcvanzee, let me clarify some points

> * the function is called get_setup_field but it returns a pair (modules, variables). So it seems to return multiple modules and variables, which is different from what the function name indicates.
> * in the function, you defined unbounded_modules, but it seems this can also be something else than modules so the name seems wrong?

The reason for this is that you can have fields with container types that include Modules e.g.

```python
def setup(self):
  self.layers = [Dense(units) for units in self.features]
```
I'd like users to be able to retrieve these so the code is generalized to work with any pytree, thats why the implementation uses `unbounded_modules` as a plural as its the most general case.

> Proposal: What do you think of the following interface?

I like the idea of this being a method, offline we decided to go for a function but happy to switch to a method. However, assuming its a method, I'd prefer this:

```python
#                                             bind args + kwargs
#                                     vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
def get_setup_field(self, field_name, variables, rngs=..., mutable=...)
````
since the `args` and `kwargs` for `bind` are grouped at the end and its super clear which field your are fetching:

```python
layers, layer_variables = module.get_setup_field('layers', variables)
```

As for the method name, `submodule` is very limiting, apart from retrieving pytrees that contain Modules, why not let the user retrieve any field? Current implementation support this:

```python
class MyModule(nn.Module):
  def setup(self):
    self.a = 1

module = MyModule()
a, _ = module.get_setup_field('a', {})

assert a == 1 and _ is None
```

> About error messages:

I agree on both points.

2022-11-17 21:03 UTC, cgarciae commented
@levskaya proposed the name `extract_field` which sounds better, there are other ideas on the table related to extracting nested subfields. I'll update the PR with some of the feedback here.

2022-11-17 21:50 UTC, levskaya commented
I think we can chat a bit about the final syntax, my main ask was that we make sure it works in the nested, recursive case - in case people have a more complicated setup where they want to pull out deeper submodules

2022-11-18 15:45 UTC, cgarciae commented
Update: here is how it looks now:

```python
class MyModule(nn.Module):
  def setup(self):
    self.submodule = nn.Dense(4)

  def __call__(self, x):
    return self.submodule(x)

module = MyModule()
variables = module.init(jax.random.PRNGKey(0), jnp.ones((1, 2)))

submodule, submodule_vars = module.extract_field('submodule', variables)
assert submodule.features == 4
```
Also works for nested object by passing a lambda as @levskaya requested:
```python
nested_module, nested_vars = module.extract_field(
  lambda m: m.some['deeply']['nested'].submodule, variables)
```
Wonder if we it should be rename as `extract_object` since its no longer just for direct fields?

2022-11-21 14:01 UTC, marcvanzee requested changes

2022-11-21 14:38 UTC, marcvanzee commented on flax/linen/module.py
> +    return unbounded_modules, variables
```suggestion
    return value, variables
```

2022-11-21 15:42 UTC, avital commented
Hi, I am curious (and nor sure I remember all of the details) -- I guess the proposed `module.extract_field('submodule', variables)` is /almost/ like doing  `Module.bind(variables).submodule`, other than the fact that the `setup` method is not automatically called until a method is run. Is this right? Maybe another alternative is then to make `bind` explicitly call `setup`? Then there's no need for a new API. Apologies if I'm totally misunderstanding this, it's been a while. I just wanted to chime in in case there's an opportunity for an API simplification.

2022-11-21 19:13 UTC, cgarciae commented
Hey @avital! `extract_field` is implemented using `bind` as you suggest. The reason why we wanted to add this API is that manually calling `.bind` is a bit unsafe, if you forget to `.clone` the Module(s) you want to extract you might get some leakage as their variables are still bounded, and `.clone` itself is more of an internal API that is not frequently exposed to users.

2022-11-21 21:12 UTC, cgarciae commented on flax/linen/module.py
> +    self = self.bind(variables, rngs=rngs, mutable=mutable)
Nice catch! This was an artifact when the function was converted to a method, renamed it to `module`.

2022-11-21 21:22 UTC, cgarciae commented on tests/linen/linen_module_test.py
> +      shapes(b_vars['params']), shapes(variables['params']['submodules_s']['b']))
Implemented

2022-11-21 21:23 UTC, cgarciae commented on flax/linen/module.py
> +    unbounded_modules = jax.tree_map(
Looking into this.

2022-11-22 13:06 UTC, marcvanzee commented
Thanks @avital for the feedback!

I think you raise some good points, and I share your worry that adding a new API on top of `bind` might be confusing for users, and this API is probably not the most intuitive one.

> what about then making bind() always call clone() first? That would allow for safe use of the module.bind().attr pattern

I don't understand this, but maybe I misunderstand you? `bind()` returns `self.clone(parent=scope)` where `scope` is bound to the passed variables [here](https://github.com/google/flax/blob/d640b5a250424baa29e42a97c72f7dec857f15e2/flax/linen/module.py#L1221). If it just clones without a bound scope as its parent then the module won't be bound, and `bind` will return a regular Module (so we cannot even do `module.bind().attr`). The reason why we `clone()` afterwards is to get back an unbound, regular Flax Module *after* we have retrieved the submodule, like this:

```py
bar_bound = foo.bind(variables).bar
bar_bound.variables  # Returns variable dict
bar = bar_bound.clone()  # bar is now a "regular" Flax Module again.
bar.variables  # ValueError: Can't access variables on unbound modules
```

Overall I am quite in favor of using `bind` instead of the proposed API, but I think we should discuss a bit more whether everyone is in favor of mixing bound modules with non-bound ones.

One reservation I have had until now with recommending users to use `bind()` is that it returns a bound (stateful) Module, which is something that may lead to other problems since we are then slightly diverging from our functional API. But maybe we should reconsider this since stateful objects do have a lot of advantages as well. We should just make sure that users don't mix them with our regular modules. We can think of various ways of doing this (e.g., we could introduce a `BoundModule` class).

2022-11-22 14:51 UTC, cgarciae commented
An alternative proposal is to have a `.snapshot` API (see #2478) that would both `clone` and extract variables at the same time e.g:

```python
bar, bar_vars = foo.bind(variables).bar.snapshot()
```
Main drawback with this API that `bind` can introduce memory leaks really easily e.g:
```python
bound_foo = foo.bind(variables)
bar, bar_vars = bound_foo.bar.snapshot()
```
This looks very innocent but `bound_foo` will contain references to `variables` even if its not used. If want to extract some pytree structure you have to do a little bit more work e.g:

```python
bound_layers = foo.bind(variables).layers
modules_vars = [layer.snapshot() if isinstance(layer, nn.Module) else (layer, None) for layer in bound_layers]
layers, layer_vars = zip(*modules_vars)
del bound_layers
```
That said, we should definitely discuss this a bit more.

2022-11-23 08:02 UTC, andsteing commented
I find the `.snapshot()` API a bit easier to use than the proposed `.extract_field()` ... especially since it builds on top of the already defined semantics of `.bind()`.

wrt memory leakage, I find that `foo_bound = foo.bind(variables)` is quite explicit about the variables being bound to `foo_bound`, so I don't think users will be surprised by this behavior.

As for your example of extracting a list of layers: I agree it's a bit verbose, but how often does this actually occur? Maybe a good reason to use `nn.Sequential` (added in #1955).

2022-11-23 09:42 UTC, marcvanzee commented
+1 to @andsteing 

Re: @cgarciae 

> This looks very innocent but `bound_foo` will contain references to `variables` even if its not used.

`bound_foo` is simply a stateful Module containing a copy of `variables`. It don't think it holds a reference to the original variables:

```py
foo_bound = foo.bind(variables)
del variables
foo_bound.variables  # Outputs the variables
```
> Also, if want to extract some pytree structure you have to do a little bit more work with this API e.g:

I think this is exactly the kind of thinking pattern we should be wary of. We do not want to implement APIs that can handle all edge cases, because there are infinitely many edge cases and this may lead down a road where we keep complicating our APIs just to handle all cases in one-liners. In your example, you collect all module sublayers into a list but also handle the case where some of these layers are not Flax Modules. Is that a common use case? If all sublayers are Flax Modules, I think you write a one-liner using `snapshot()`:

```py
layers, layers_vars = zip(*(l.snapshot() for l in foo.bind(variables).layers))
```

I am just wondering about the naming of `snapshot()`. Wouldn't it be clearer to use `bind()` and `unbind()`? Then you get:

```py
layers, layers_vars = zip(*(l.unbind() for l in foo.bind(variables).layers))
```

2022-11-23 13:16 UTC, cgarciae commented
Thanks everyone for the feedback! Let me explain how we reached this API and then I'll share my thoughts.

For the Transfer Learning guide we originally had code like this to extract a submodule:

```python
bar_bounded = foo.bind(variables).bar
bar = bar_bounded.clone()
bar_vars = bar_bounded.variables
del bar_bounded
```
We want to delete `bar_bounded` because it contains references to JAX arrays in its `scope`. @jheek then propose to avoid `bind` altogether by using `nn.apply` and a helper function:
```python
def extract_bar(foo):
  bar = foo.bar.clone()
  bar_vars = foo.bar.variables
  return bar, bar_vars
  
bar, bar_vars = nn.apply(extract_bar, foo)(variables)
```
Then it was proposed that we generalized this pattern as it might be frequently used, so we created the `extract_field` method resulting in:

```python
bar, bar_vars = foo.extract_field('bar', variables)
```

#### unbind
Extracting a submodule or field via `unbind` can be also done if done in a single like line:

```python
bar, bar_vars = foo.bind(variables).bar.unbind()
```
This is probably enough for the majority of the use cases. 

#### Summary
The case for `extract_field` is that its a lot safer, does more for the user (works with pytree fields), and requires learning less concepts (no need to learn about `bind`). The case for `unbind` is that it promotes the use of the existing `bind` API so the user has more clarity of what is happening, at the cost of having to deal with some edge cases.

I am happy with both, lets discuss this in  our next sync.

2022-11-23 14:23 UTC, andsteing commented
Thanks for the summary, Cristian!

Could you elaborate a bit on the points

1. "safety" : what's unsafe about writing `foo.bind(variables).bar.unbind()`?
2. "pytree fields" : couldn't one simply write `foo.bind(variables).layers[0].unbind()`?

2022-11-23 14:31 UTC, marcvanzee commented
Thanks for the overview @cgarciae!

> We want to delete `bar_bounded` because it contains references to JAX arrays in its scope

I think it isn't surprising that a bound module contains variables. As Andreas said, we should be careful with naming though. I kind of like the bind/unbind pattern in a single line, but curious what others think!

2022-11-23 15:12 UTC, cgarciae commented
@andsteing if you do it in a single line its all good:
```python
bar, bar_vars = foo.bind(variables).bar.unbind()
```
but if you split it into 2 lines suddenly you have to be more careful with memory:
```python
bar_bound = foo.bind(variables).bar
bar, bar_vars = bar_bound.unbind()
del bar_bound
```

2022-11-23 16:31 UTC, avital commented
Here's another possible semi-hacky solution -- verify in runtime when you call `unbind()` that there are no additional referrers to the module being unbound. This small example I did in a Colab shows that it could catch the difference between calling a method directly on a created object vs storing the object in a variable and calling it there: (this definitely may have some other problems! but it's an idea)

```py
import gc
class Foo:
  def __init__(self, depth):
    if depth > 0:
      self.sub = Foo(depth-1)

  def __call__(self):
    print(f"num referrers: {len(gc.get_referrers(self))}")

foo = Foo(2)
foo.sub()
# prints:
# num referrers: 1

Foo(2).sub()
# prints:
# num referrers: 0
```

2022-11-24 12:47 UTC, marcvanzee commented
Thanks for the input @avital 

> maybe there's an adjustment to the API that makes the bound modules only work within a with block, e.g.:

I also considered this actually, and it seems indeed quite safe. I am personally just not such a big fan of context managers in Python. TF is full of them, Flax pre-Linen had them as well, and I always find it more difficult to reason about what is going on when I use them. But if others like it: I am not against it in principle.

> Here's another possible semi-hacky solution -- verify in runtime when you call unbind() that there are no additional referrers to the module being unbound.

I don't fully get this, what do you want to do then if there are no additional referrers? Put the object in some kind of "deactivated" state? Or do you want to disallow calling `unbind()` after creating the object?

I think I am still in favor of recommending the bind/unbind pattern in one line, and then telling clearly that if someone binds a module it has a state.

@levskaya also curious to hear what you think. Do you think users will start making mistakes if we start advertising using `bind()` for these kinds of use cases?

2022-11-24 13:35 UTC, avital commented
> I don't fully get this, what do you want to do then if there are no additional referrers? Put the object in some kind of "deactivated" state? Or do you want to disallow calling unbind() after creating the object?

My proposal with checking the number of referrers would be to make `unbind()` raise an error if there are >0 referrers, basically forcing the logic to happen in one line. But again, there are probably unintended consequences here. That being said, relaxing a constraint later is easier than introducing a constraint and fixing a bunch of user code.

2022-12-08 12:26 UTC, marcvanzee commented
@avital we decided to favor the `bind`/`unbind` pattern over the `extract_field` method, see #2674. Rather than adding reference counting tricks (which feels a bit brittle), @cgarciae is going to write a guide explaining how to safely use this API (see #2689 -- which is still WIP). Thanks again for your input and please keep giving us feedback, it is extremely valuable!

@cgarciae I suppose we can close this PR now?

2022-12-08 13:39 UTC, cgarciae commented
Yes. Thanks @avital for sparking the conversation!

2022-12-08 13:39 UTC, closed without merging