added Einsum layer to NNX
google/flax pull request #3741
Opened 2024-03-05 02:45 UTC by chiamp

The NNX implementation of the `Einsum` layer requires an explicit `input_shape` to be passed at construction time since the bias param is instantiated during construction time and requires that information. A dummy array is constructed using [`jax.ShapeDtypeStruct`](https://jax.readthedocs.io/en/latest/_autosummary/jax.ShapeDtypeStruct.html#jax.ShapeDtypeStruct)) and is passed to [`opt_einsum.parser.parse_einsum_input`](https://github.com/dgasmith/opt_einsum/blob/master/opt_einsum/parser.py#L265) (in the case of the Linen implementation, [both arrays are provided during call time](https://github.com/google/flax/blob/main/flax/linen/linear.py#L391)).

While both implementations allow `einsum_str` to be passed during construction and call time, the bias shape can be determined either by the `einsum_str` passed in constructor or call time because of lazy init in Linen, while the bias shape is always determined by the `einsum_str` passed in construction time in NNX (meaning it must always be passed during construction time). NNX allows the option to pass in a different `einsum_str` during call time which will take precedence over the constructor `einsum_str`, but the bias shape is never determined at call time, since it's already been instantiated.

2024-03-05 14:54 UTC, cgarciae commented
I think it would be cleaner if the user provides `bias_shape` and that way we don't even need `_get_bias_shape` and the einsum parsing machinery.

2024-03-05 17:48 UTC, chiamp commented
> I think it would be cleaner if the user provides the `bias_shape` instead of the `input_shape`. This way we don't even need `_get_bias_shape` and the einsum parsing machinery.

I originally wrote it this way. The user would also have to provide `broadcasted_bias_shape` as well; my thought process was that it would be easier for the user to just provide the `input_shape`. What if we allow the user to pass in either `input_shape` (in which bias shape would be inferred), or `bias_shape` and `broadcasted_bias_shape` (in which bias shape is specifically passed)? The constructor signature could be something like:
```
def __init__(
    self,
    einsum_str: str,
    kernel_shape: Shape,
    input_shape: tp.Optional[Shape] = None,
    bias_shape: tp.Optional[Shape] = None,
    broadcasted_bias_shape: tp.Optional[Shape] = None,
    *,
    ...
```

2024-03-14 11:53 UTC, cgarciae requested changes

2024-03-14 11:53 UTC, cgarciae commented on flax/experimental/nnx/nnx/nn/linear.py
> +    >>> layer = nnx.Einsum((3, 4, 5), (5, 6, 7), 'abc,cde->abde', rngs=nnx.Rngs(0))
```suggestion
    >>> layer = nnx.Einsum('abc,cde->abde', (3, 4, 5), (5, 6, 7), rngs=nnx.Rngs(0))
```

2024-03-14 11:53 UTC, cgarciae commented on flax/experimental/nnx/nnx/nn/linear.py
> +    use_bias: bool = True,
Maybe `bias_shape` being present or not is enough and we don't need `use_bias`?

2024-03-14 11:54 UTC, cgarciae approved these changes

2024-03-14 21:00 UTC, merged