[nnx] add full_update
google/flax pull request #3826
Opened 2024-04-04 16:43 UTC by cgarciae

# What does this PR do?

WIP

2024-04-14 13:07 UTC, superbobry requested changes
I cannot really evaluate these new APIs properly. I would recommend adding another Flax contributor as a reviewer.

2024-04-14 13:07 UTC, superbobry commented on flax/experimental/nnx/nnx/graph_utils.py
> +    # refmap is opaque
What is `refmap` here and below?

2024-04-14 13:07 UTC, superbobry commented on flax/experimental/nnx/nnx/graph_utils.py
> +def full_split(
Please ad a docstring for this and the other new APIs.

2024-04-17 15:18 UTC, cgarciae commented on flax/experimental/nnx/nnx/graph_utils.py
> +    # refmap is opaque
removed this, no longer relevant

2024-04-18 09:37 UTC, superbobry requested changes

2024-04-18 09:37 UTC, superbobry commented on flax/experimental/nnx/nnx/graph_utils.py
> +    return 0
This will make all instance hash to the same value. Why is it safe?

2024-04-18 09:37 UTC, superbobry commented on flax/experimental/nnx/nnx/graph_utils.py
> +def full_split(
The docstrings are still missing in the latest version. Do you think they are unnecessary and the signatures are sufficient?

2024-04-22 07:55 UTC, closed without merging