upgraded haiku guide to include NNX
google/flax pull request #3923
Opened 2024-05-14 01:33 UTC by chiamp

upgraded haiku guide to include NNX

2024-05-23 10:22 UTC, cgarciae commented on docs/experimental/nnx/haiku_linen_vs_nnx.rst
> +Haiku and Linen vs NNX
I think we should call the "Migrating from Haiku/Linen to NNX"

2024-05-23 11:09 UTC, cgarciae requested changes

2024-05-23 16:05 UTC, chiamp commented on docs/experimental/nnx/haiku_linen_vs_nnx.rst
> +user to switch between stateful and stateless modules.
I'll also change the tabs to Linen and NNX

2024-05-23 16:07 UTC, chiamp commented on docs/experimental/nnx/haiku_linen_vs_nnx.rst
> +    nnx.update(model, params)
change this for both the dropout and batch norm example

2024-05-23 16:08 UTC, chiamp commented on docs/experimental/nnx/haiku_linen_vs_nnx.rst
> +      return optax.softmax_cross_entropy_with_integer_labels(logits, labels).mean()
do this for all train steps

2024-05-24 09:23 UTC, cgarciae commented on docs/experimental/nnx/haiku_linen_vs_nnx.rst
> +    return state
```suggestion
  def train_step(state, inputs, labels):
    def loss_fn(params, batch_stats):
      logits, (graphdef, new_state) = state.apply_fn(
        params, batch_stats


      )(inputs) # <== inputs
      _, batch_stats = new_state.split(nnx.Params, nnx.BatchStats)
      loss = optax.softmax_cross_entropy_with_integer_labels(logits, labels).mean()
      return loss, batch_stats

    grads, batch_stats = jax.grad(loss_fn, has_aux=True)(state.params, state.batch_stats)

    state = state.apply_gradients(grads=grads)
    state = state.replace(batch_stats=batch_stats)

    return state
```

2024-06-03 07:06 UTC, cgarciae approved these changes

2024-06-03 16:11 UTC, merged