Allow metadata pass-through in flax.struct.field
google/flax pull request #4056
Opened 2024-07-04 14:21 UTC by cool-RR

# What does this PR do?

Allows passing through `metadata` when creating a `flax.struct.field`. This is useful when you want to add some metadata to your field to be read later.

## Checklist
- [ ] This PR fixes a minor issue (e.g.: typo or small bug) or improves the docs (you can dismiss the other
      checks if that's the case).
- [ ] This change is discussed in a Github issue/
      [discussion](https://github.com/google/flax/discussions) (please add a
      link).
- [ ] The documentation and docstrings adhere to the
      [documentation guidelines](https://github.com/google/flax/blob/main/docs/README.md#how-to-write-code-documentation).
- [ ] This change includes necessary high-coverage tests.
      (No quality testing = no merge!)

2024-07-09 21:48 UTC, IvyZX requested changes
Thanks for making this change! Can we have a test for this?

2024-07-09 22:14 UTC, cool-RR commented
@IvyZX Pushed a test, let me know if anything else is needed.

2024-07-09 23:31 UTC, IvyZX approved these changes
Thank you! Approved. You would need to pull and rebase for a trivial merge conflict.

2024-07-10 07:35 UTC, cool-RR commented
@IvyZX Fixed.

2024-07-19 20:46 UTC, cool-RR commented
@IvyZX Are we awaiting some automated process to get this merged?

2024-08-05 14:16 UTC, cool-RR commented
@IvyZX Is this good for merging?

2024-08-05 15:39 UTC, merged