Adding Conv2DLSTM
google/flax pull request #422
Opened 2020-08-21 16:59 UTC by mbz

Mostly ported from Haiku implementation.

2020-08-25 14:36 UTC, avital commented
Hi @mbz, thanks for the PR! Can you please add a test, similar to the ones we have in RecurrentTest for LSTMs? https://github.com/google/flax/blob/master/tests/nn_test.py#L623

2020-08-27 20:49 UTC, mbz commented
Added a test.
Added to nn.__init__
Renamed to ConvLSTM.

2020-09-01 09:08 UTC, jheek requested changes

2020-09-01 09:08 UTC, jheek commented on flax/nn/recurrent.py
> +    f = jnn.sigmoid(f + 1)
nit: you can just use `nn.sigmoid` here avoiding the jnn import

2020-09-01 09:08 UTC, jheek commented on flax/nn/recurrent.py
> +    new_h = jnn.sigmoid(o) * jnp.tanh(new_c)
here as well

2020-09-01 09:08 UTC, jheek commented on flax/nn/recurrent.py
> +from jax import nn as jnn
this import shouldn't be needed see below

2020-09-03 19:56 UTC, avital commented
@jheek can you please give this a final review and if it's OK merge it? (or if you want to make minor changes you can push straight to the mbz/flax:patch-1 as well)

2020-09-07 12:50 UTC, jheek approved these changes
looks good to me

2020-09-08 12:36 UTC, merged