Fail with a better error message on invalid variable structure in `Module.apply()`
google/flax pull request #504
Opened 2020-09-30 13:51 UTC by mohitreddy1996

#489 - if the collection of variables of a kind is immutable and the variable doesn't exist in the collection, we cannot initialize it (even if the RNGs are provided).

2020-10-01 15:11 UTC, avital commented
Can you please add a test?

Also I'd like a second review from @jheek to see if I didn't miss any edge case.

2020-12-12 23:12 UTC, avital commented
Wow, I had PR comments from months ago that were unsubmitted :( Apologies @mohitreddy1996 -- do you think you want to get this PR updated and merged? Alternatively, if you're busy maybe best to close the PR in the meanwhile

2021-01-05 15:28 UTC, jheek commented
@mohitreddy1996 -- this PR has a merge conflict now. Could you take a look?

2021-03-02 10:07 UTC, marcvanzee requested changes

2021-03-02 10:07 UTC, marcvanzee commented on flax/core/scope.py
> +      raise ValueError(f"Kind: {col} is immutable and "
Could you use a custom error message instead? https://github.com/google/flax/blob/master/flax/errors.py

2022-02-03 15:35 UTC, avital commented
This PR is inactive, and the original issue (#489) has been resolved. So I'm closing it.

2022-02-03 15:35 UTC, closed without merging