use core reservation check in linen.
google/flax pull request #538
Opened 2020-10-16 14:40 UTC by jheek

Also solves a bug in the clone method
which was silently sharing PRNG sequences

2020-10-22 11:51 UTC, avital commented
This looks correct to me but I don't remember why we were trying to disable the scope reservation check to begin with. @levskaya do you remember?

2020-10-22 11:51 UTC, avital approved these changes

2020-10-23 06:06 UTC, levskaya commented
Well we disabled it because we were doing our own name-reservation handling, perhaps at the time because we had to for some short-lived reason while we were prototyping things.

2020-10-23 06:07 UTC, levskaya approved these changes

2020-10-23 06:11 UTC, levskaya requested changes
I think this PR needs to be rebased on master and an extra `self._state.reservations` reference needs to be removed from the updated `self.param()` fn at head.  I think that's what's causing the failing tests below.

2020-10-27 06:29 UTC, levskaya approved these changes

2020-10-27 07:48 UTC, merged