Updates top-level doc-string of functional core Scopes
google/flax pull request #588
Opened 2020-11-03 09:24 UTC by marcvanzee

2020-11-03 12:23 UTC, jheek requested changes
I have a few comments. I think we need to iterate on this some more to really make scopes easy to understand from the docstring

2020-11-03 12:23 UTC, jheek commented on flax/core/scope.py
> +non-trainable parameters `moving_mean` and `moving_average`.
I am missing the explanation of how users actually access params using scope. Shouldn't you have things like `scope.variable` and `scope.param` here?

2020-11-05 08:18 UTC, andsteing commented on flax/core/scope.py
> +instance within an instance of the BatchNorm layer, the programmer has easy
Nit: "instance within an instance" - maybe "example within an instance" ?

2020-11-05 08:18 UTC, andsteing commented
Linking this to #593

2020-11-10 09:45 UTC, jheek requested changes

2020-11-10 09:45 UTC, jheek commented on flax/core/scope.py
> +a function that expects RNG keys for all collections::
rng sequenced and collections aren't linked (except for paramaters).  But there is no 'batch_stats' rng

2020-11-10 09:45 UTC, jheek commented on flax/core/scope.py
> +Thus, the user provides rng seeds for all collections to the top-level scope,
to explain RNGs better we might need to show `scope.make_rng('some_name')`

2020-11-10 09:45 UTC, jheek commented on flax/core/scope.py
> +The functional core Scope defined below allows easy access to all variables in a
nit: perhaps keep class names quoted for highlighting so Scope -> `Scope`

2020-11-10 09:45 UTC, jheek commented on flax/core/scope.py
> +This will initialize it using `jnp.zeros` with shape `(,)`. The function
this shape here I find a bit confusing. `(,)` is the same as `()` which is a scalar. But batch stats are not scalars

2020-11-10 09:45 UTC, jheek commented on flax/core/scope.py
> +      "BatchNorm1": { "moving_mean": ..., "moving_average": ...}
nit: moving_mean and moving_average are the same thing. Normally we have ema_mean and ema_variance

2020-11-17 15:29 UTC, jheek approved these changes

2020-11-17 15:51 UTC, merged