Add "extracting intermediates" pattern doc
google/flax pull request #771
Opened 2020-12-29 07:44 UTC by avital

Adds a page under docs/patterns/ for ways to extract intermediate
values from a model. One of the ways suggests using `put_variable`,
which this commit also adds back.

I propose that this format replace our previous HOWTO system, and
we use this to document many of our other patterns, and rewrite
all HOWTOs this way.

Thus, I am looking for a very careful review.

TODO:
- [ ] Add unit tests. (The doc itself is an integration test)
- [ ] Add a docstring to `put_variable`
- [ ] Clone submodules when assigning to `self.layers` in `Sequential`
      so that we can safely reuse the same `CNN` instance.

ADDITIONAL CHANGES
------------------
* Remove the HOWTO system. It was clunky and added maintenance
  burden to all example editors. Instead, this document contains
  `testcode` blocks which means that it is tested directly from
  within the doc, without depending on any examples.

* Add support for tests embedded within docs. This allows for
  writing docs that "feel like" notebooks, but are easier to edit,
  and allow hiding imports and other initialization in `testsetup`

* Allow taking in non-frozen collections in `apply` (resolves #719).

QUESTIONS
---------
1. Is it weird that we need to pass in an empty intermediates collection
   if we want to use `put_variable`? We already specify that we expect
   changes to that collection via `mutable=['intermediates']`.
   We could try making `mutable=['intermediates']` add an additional
   intermediates collection if it's not there but then we'd have to
   theoretically also support `mutable=[True, 'intermediates']`.
   Another alternative is to add another option like mutable with
   an explicit list of collection names that are "output-only"

2. Is the `put_variable` implementation, which allows for either
   receiving intermediate outputs or not based on whether you pass
   in an `intermediates` variable collection good? Otherwise, people
   would have to thread in additional attributes to keep track or
   whether they want to return intermediate outputs or not.

3. Is the pattern in `Sequential` weird? In `setup`, we run
   `self.layers = self.submodules` to bind unbound modules. It's
   hard for users to understand this. I haven't thought too deeply
   about a possible better solution.

2021-01-05 10:05 UTC, jheek commented
I think we should have something like `put_variable` but there a few tricky details:

1. It should have the "ignore if not mutable" semantics but this is different from the other methods which fail if something isn't mutable. So ideally the method name already suggests that this is not a standard read/write get/put style api for variables.

2. We probably shouldn't silently override existing values. Because there will be 2 common issues with tracking intermediates: Accidentally keeping them around and feeding them back into apply (memory leak). And we can have multiple intermediates when using shared modules. So a more general version could be:
```
def record(self, name, value, col='intermediate'):
 """Records a value if the target collection is mutable. By default the 'intermediate collection is used.
     Returns True if the collection is mutable and False otherwise."""
  if not self.is_mutable(col):
    return False
  var = self.variable(col, name, lambda: ())
  var += (value,)
  return True
```

2021-01-05 10:08 UTC, jheek commented
>> Is it weird that we need to pass in an empty intermediates collection
if we want to use put_variable

Are you sure this is the case? As far as I remember a collection just has to mutable it doesn't need to be passed in

2021-01-05 11:53 UTC, avital commented
> > > Is it weird that we need to pass in an empty intermediates collection
> > > if we want to use put_variable
> 
> Are you sure this is the case? As far as I remember a collection just has to mutable it doesn't need to be passed in

2021-01-18 12:43 UTC, marcvanzee commented
General question: why did you use the term "pattern" in this PR instead of HOWTO? The PR description states "Adds a page under docs/patterns/ ...", but it actually seems to add it under doct/howtos. Did you first think of switching to patterns and then went back to howtos? It seems clearer to me when we use one of the two consistently, because now I was thinking that patterns weren something different than howtos.

2021-01-18 14:15 UTC, avital commented
I'm not sure I thought about it too carefully, I think patterns and HOWTOs are the same thing. This is very much still a WIP PR, happy to follow your lead @marcvanzee on wherever we decide to put things and how we decide to call them.

2021-01-19 11:48 UTC, marcvanzee requested changes
Two high-level questions:

1. Can we see the resulting HOWTO in a readthedocs somewhere? Is it running on the server or should I compile it myself?
2. Can we split off the suggested change to core in a separate PR and get that in first? It seems @jheek has some comments, and this discussion may be helpful to users (and us) later on, so it seems clearer to have that in a separate PR.

2021-01-19 11:48 UTC, marcvanzee commented on .github/workflows/build.yml
> +        sphinx-build -M doctest docs docs/_build
This is supercool 😄  Maybe it can replace Colabs all together?

2021-01-19 11:48 UTC, marcvanzee commented on docs/howtos/extracting_intermediates.rst
> +Because this module uses ``nn.compact``, we don't have direct access to
I think this deserves a bit more explanation. Why don't we have access to values if we are using `nn.compact`? Aren't all these `x`'s intermediate values? Or do you mean access from the outside?

If we weren't using `compact` but we weren't exposing the intermediate values, we would also not have access to them, right?

2021-01-19 11:48 UTC, marcvanzee commented on docs/howtos/extracting_intermediates.rst
> +You can augment any module with calls to ``put_variable``
Why are these lines so short? Or perhaps it won't show up on RTD?

2021-01-19 11:48 UTC, marcvanzee commented on docs/howtos/extracting_intermediates.rst
> +    # `mutable=['intermediates']` specified which collections are treated as
```suggestion
    # `mutable=['intermediates']` specifies which collections are treated as
```

2021-01-19 11:48 UTC, marcvanzee commented on docs/howtos/extracting_intermediates.rst
> +  features(params, batch)
It is odd that these two functions return something but we aren't using the returned result. Did you forget it?

2021-01-19 11:48 UTC, marcvanzee commented on docs/howtos/extracting_intermediates.rst
> +
Why aren't we predicting here anymore?

2021-01-19 11:48 UTC, marcvanzee commented on docs/howtos/extracting_intermediates.rst
> +Extracting intermediate values
What do you think of adding something like a TL;DR at the top with the three suggested approaches?

2021-01-19 11:48 UTC, marcvanzee commented on docs/howtos/extracting_intermediates.rst
> +  def init(key, x):
Nit: If you rename each module differently you only have to define `init` once if you provide the module name as an argument.

2021-02-24 14:43 UTC, avital commented
Superceded by #1043

2021-02-24 14:43 UTC, closed without merging